### PR TITLE
add happi support

### PR DESCRIPTION
**Pull request by untzag**
Adds support for happi [1], including `HappiItem` class for yaq and `happi.containers` entry point. See associated PR at happi [2].

Also sneaking in unpinning pre-commit Python version...

[1] https://pcdshub.github.io/happi/
[2] https://github.com/pcdshub/happi/pull/191

TODO:
- [x] functionality
- [x] testing
- [x] documentation

### CODE REVIEW

**Comment by untzag** [comment]
why isn't pytest running? :thinking:

**Comment by untzag** [comment]
I clearly still don't understand happi internals.

The following works:
```python
import tempfile
import happi
import yaqc_bluesky

item = yaqc_bluesky.happi_containers.YAQItem(name="test", port=38999)
with tempfile.NamedTemporaryFile() as f:
    backend = happi.backends.backend(f.name)
    happi_client = happi.Client(database=backend)
    happi_client.add_device(item)
    output = happi_client.find_device(name="test")
    print(output)
```

The following does NOT work:
```python
import tempfile
import yaqc_bluesky
import happi

item = yaqc_bluesky.happi_containers.YAQItem(name="test", port=38999)
with tempfile.NamedTemporaryFile() as f:
    backend = happi.backends.backend(f.name)
    happi_client = happi.Client(database=backend)
    happi_client.add_device(item)
    output = happi_client.find_device(name="test")
    print(output)
```

Only order of imports changed.

I believe that this problem has to do with the happi registry [1]. Somehow order matters... if our class is added before the entry point vs after, or something like that. In the second example, the error raised says "None is not a subclass of HapiItem" [2].

[1] https://github.com/pcdshub/happi/blob/master/happi/containers.py#L18
[2] https://github.com/pcdshub/happi/blob/master/happi/client.py#L216

I'm planning to return to this... sometime.

**Comment by ksunden** [comment]
closing and reopening to retrigger ci

**Comment by ksunden** [comment]
Okay, so... I suspect it will run on the next push...

When I clicked on the "actions" tab on github, it said that the python test and bluesky-git actions were disabled because of inactivity for 60 days... I feel like it _should_ have kept the push trigger, but maybe it doesn't.

I reenabled them and tried to get it to run again, but it didn't 

I suspect if we added "pull-request" in addition and/or instead of "push" that would also affect the close/reopen behavior

**Comment by untzag** [comment]
Wait... what? Our CI just gets turned off if we don't use it for a while?

That's not okay...

**Comment by ksunden** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/disabling-and-enabling-a-workflow

Its kind of hidden in the gh actions docs,  not mentioned in the section about scheduled actions.

It seems like there is not separate "disable/enable" flags for the different triggers... so any action that has scheduled gets disabled after 60 days of repo inactivity...

**Comment by untzag** [comment]
turns out this is a bug (in my opinion) within happi, see https://github.com/pcdshub/happi/issues/198

**Comment by untzag** [comment]
fixed in happi, now just waiting for release

**Review by ksunden — APPROVED** [review]

**Pull request merged**
